### ISSUE TITLE
Will this work on mac?

### ISSUE THREAD

**Issue by reetteerrs** [opiter09/Fossil-Fighters-Randomizer#1]
Hi!  I'm so excited for this, I've waited so long for a FF randomizer.  But I've already run into an issue.  I'm on Mac, I've downloaded all the files, and I have the FF rom in the same folder as the files.  But because I'm on Mac, nothing happens when I drop the rom file onto the randomize.exe file.  I also can't open the randomize.exe file or do anything with it.  Do you have any suggestions on what I can do?

**Comment by opiter09** [comment]
I'm gonna have to just point you to WINE on this. I have no idea how it works and I cannot help you with it, but it should allow you to run Windows programs on Mac: https://www.winehq.org/
