### ISSUE TITLE
Guaranteed V-Raptor does not appear until both fossil chips are owned

### ISSUE THREAD

**Issue by the-Lazarator** [opiter09/Fossil-Fighters-Randomizer#2]
I'd been going to the keymonite room over and over to grab it for the eventual Holt fight as soon as the room was available, it was never appearing

Tried going through the story beats and checking after each one, it still wasn't spawning

Got to the point I had to fight Holt and needed V-Raptor and gave it 10 more visits to the room, still nothing.

bought the first fossil chip, same story

Suddenly, after getting the second fossil chip, that is when V-Raptor finally spawned

This forces the player to grab both fossil chips fairly early into the game, forcing grinding if they don't use cheats, forcing the player to sift through more rocks in dig sites earlier than they may like, and offsetting the balance of the game as a player may inadvertently get themselves very high level Vivosaurs for this point in progression simply due to having all the chips already. Obviously this is a bug and not intentional so I do not bring these issues up to shame, simply to point out the reason the bug needs fixing if possible

There's a possibility that this is linked to other sonar upgrades, as I had a maxed fossil filter and sonar size before even my first visit to the Digadigamid; but I'd have to restart the whole game to test if these also have an effect on V-Raptor finally appearing.

**Comment by opiter09** [comment]
As you can probably guess, I tested that room working using a post-game save. So this will definitely be looked into.

**Comment by opiter09** [comment]
this should be fixed now. not sure if you still have an older save to confirm, but let me know if there are issues

**Comment by Concordia69** [comment]
I have tested it and it seems to have worked. Thanks and keep up the good work!
