### ISSUE TITLE
V-Raptor is not at the Digadigamid

### ISSUE THREAD

**Issue by ThatRandomSpriter** [opiter09/Fossil-Fighters-Randomizer#4]
I've only just recently discovered this randomizer and was really eager to play it. However I have run into a very prominent issue; the V-Raptor fossils are nowhere to be seen in the Digadigamid's Keymonite room. I'm aware this issue has been reported before, however I did acquire every upgrade possible for the Sonar, Fossil Case and Cleaning Tools. To do so in a quick fashion, I did use a cheat code for maximum money however I don't think that should have caused any issues. Repeated visits to this room in the Digadigamid has not changed anything and I am unsure as to what to do about this.

**Comment by opiter09** [comment]
Okay I think I know what happened. Normally dig sites have fossils for 0, 1, and 2 chips. I changed the keymonite's fossils from 2 chips to 0, solving the precious issue. However, I now created the opposite problem, and this fossils are *only* available with no chips. Given when you need them in the story, this isn't a huge deal to me, but I will put it in the Readme. So thanks for finding it out!

**Comment by ThatRandomSpriter** [comment]
Anytime, though now it sounds like I'm left with no choice but to start all over again from the beginning because I'm at the point in the game where I need V-Raptor but because I have the Fossil Chips, it'll never spawn.
