### ISSUE TITLE
Can't get V-Raptor

### ISSUE THREAD

**Issue by GoldH2O** [opiter09/Fossil-Fighters-Randomizer#5]
Hey, so I know this is the third time this has been posted on here, but I'm having issues with the guaranteed V-Raptor. I don't have either fossil chip, but I do have the other four sonar upgrades before them. I also got the v-raptor legs from the captain if that has anything to do with it. Anyway, in the keymonite room I'm able to find the body, legs, and arms of v-raptor, but after visiting 26 times I haven't gotten a single head. Am I just getting terrible RNG or is there something wrong here?

**Comment by opiter09** [comment]
Did you get all three on one save? because if you have no chips, you shouldn't be able to get all four parts, in which case there must be an actual issue.

**Comment by GoldH2O** [comment]
Yes, all on one save. I'm not getting the exact same three fossils every time I go into the room, though. Sometimes it's two arms and one body or three legs, or whatever. Just no heads.

**Comment by opiter09** [comment]
Hmmmm... can you send your save file, and the file "out.xdelta" which the randomizer generated?

**Comment by GoldH2O** [comment]
I will do that as soon as I can

**Comment by GoldH2O** [comment]
Here's the files: 
[Uploading FF Save.zip…]()

**Comment by GoldH2O** [comment]
Here's the files. Github wouldn't let me upload them here for some reason so I stuck em in drive.

[https://drive.google.com/file/d/11gdwhx2uctg93EhwWx9LZhVODCOAdUH3/view?usp=sharing](url)

**Comment by opiter09** [comment]
So I am definitely seeing the all-parts thing, but when I renamed your save to work with another randomized ROM I had, I did manage to get a head on my first trip in. I do think this is a luck thing then, although that is partially my fault for only putting three fossils in the room. I may add more now that I know it's split between four parts, not two.

**Comment by opiter09** [comment]
Okay it is updated to have 9 fossils instead of 3. Here is an xdelta format patch file you can apply to your ROM so you don't have to start over. The easiest way to apply this patch is with https://www.romhacking.net/patch/ [sevensies.zip](https://github.com/opiter09/Fossil-Fighters-Randomizer/files/13848124/sevensies.zip)

**Comment by opiter09** [comment]
I did just manage to get a head on the edited version of yours, so it is not impossible, but definitely very hard for some odd reason.

**Comment by GoldH2O** [comment]
Alright, thank you!
